### PR TITLE
Iam role check

### LINKED ISSUE #22: [New Check] Roles in an AWS account
The AWS console is warning us about getting close to the limit for number of IAM roles (1000).  Would like to have a check for this limit.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-entities

### PR DESCRIPTION
**Pull request by charleshepner**
Check for the number of IAM roles in an account.

Fixes #22

### CODE REVIEW

**Comment by brennerm** [comment]
@charleshepner Thanks for opening this PR. Unfortunately the service code you are referencing does not exist for my AWS account:
```
...
botocore.errorfactory.NoSuchResourceException: An error occurred (NoSuchResourceException) when calling the GetServiceQuota operation: 
...
botocore.errorfactory.NoSuchResourceException: An error occurred (NoSuchResourceException) when calling the GetAWSDefaultServiceQuota operation: The request failed because the specified service does not exist.
```
Did you request a quota increase for the number of roles in your AWS account?

**Comment by charleshepner** [comment]
We had 835 roles out of 1000 in our prod account, so the AWS console was warning us, which was what led me to create this check.  Here are some screenshots from two of our accounts:

nonprod
image

prod
image

I did ask for a quota increase to 2000 for our prod account.  It looks as if our nonprod account has an increase applied as well, but that must have been some time ago since I don't recall submitting a ticket for that.

**Comment by brennerm** [comment]
Yeah so it seems like these limits are only available after a quota increase. I'm OK with returning the default value of 1000 if getting the limit returns a `botocore.errorfactory.NoSuchResourceException`. Do you want to implement this behavior?

**Comment by charleshepner** [comment]
Yep, sure thing.

**Comment by brennerm** [comment]
Implemented in https://github.com/brennerm/aws-quota-checker/commit/da7b983f4ee9eefd84d4ecbd1da2b0bbe1b30452

**Pull request closed without merging**
